name: libusb
description: A simple command-line application.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  ffi: ^0.1.3

dev_dependencies:
  pedantic: ^1.9.0
  ffigen: ^1.2.0

ffigen:
  name: Libusb
  description: Bindings to `libusb.h`.
  output: 'lib/libusb.dart'
  headers:
    entry-points:
      - 'libusb-1.0/libusb.h'